version: '3'
services:
  mongodb:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    expose:
      - '27017'
  nodejs:
    image: jacksonrayhamilton/urbantreasure-nodejs
    expose:
      - '3000'
    depends_on:
      - mongodb
  nginx:
    image: jacksonrayhamilton/urbantreasure-nginx
    ports:
      - '80:80'
    depends_on:
      - nodejs
volumes:
  db-data:
