version: '3'
services:
  mongodb:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    ports:
      - '27017:27017'
  nodejs:
    build:
      context: .
      dockerfile: nodejs.prod.Dockerfile
    expose:
      - '3000'
    depends_on:
      - mongodb
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - nodejs
volumes:
  db-data:
