version: '3'
services:
  nodejs:
    build: .
    expose:
      - '3000'
  nginx:
    image: nginx:1.20
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - nodejs
