version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    ports:
      - '27017:27017'
  nodejs:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
    volumes:
      - ./dist/:/usr/src/app/dist
    expose:
      - '3000'
    depends_on:
      - mongodb
  nginx:
    image: nginx:1.20
    volumes:
      - ./dist/public_html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - nodejs
volumes:
  db-data:
